# Generated by Django 5.0.1 on 2024-01-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(default='Sebaxe09', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_icon',
            field=models.CharField(default='tiger.svg', max_length=100),
        ),
    ]
