name: Run tests and notify backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        id: tests
        continue-on-error: true
        run: |
          output=$(python -m unittest discover 2>&1 || true)
          echo "Test output: $output"
          failed=$(echo "$output" | grep -o 'FAIL:' | wc -l)
          total=$(echo "$output" | grep -o 'Ran [0-9]* tests' | grep -o '[0-9]*')
          echo "Failed tests: $failed"
          echo "Total tests: $total"
          passed=$((total - failed))
          echo "PASSED=$passed" >> $GITHUB_ENV
          echo "TOTAL=$total" >> $GITHUB_ENV
          echo "$output"
      - name: Notify backend
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "commit_sha":"${{ github.sha }}",
            "branch":"${{ github.ref }}",
            "commit_message":"${{ github.event.head_commit.message }}",
            "author":"${{ github.actor }}",
            "repo":"${{ github.repository }}",
            "tests_passed":${{ env.PASSED }},
            "tests_total":${{ env.TOTAL }}
          }' \
          https://dl529nfz-8000.euw.devtunnels.ms/aes/webhook-endpoint
