# Generated by Django 5.0.1 on 2024-01-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('min_students_per_group', models.PositiveIntegerField()),
                ('max_students_per_group', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('battles', models.ManyToManyField(related_name='tournaments', to='tournament_management.battle')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to='user_management.educatorprofile')),
                ('invited_Educators', models.ManyToManyField(related_name='invited_tournaments', to='user_management.educatorprofile')),
                ('rankingScores', models.ManyToManyField(related_name='tournaments', to='user_management.studentprofile')),
            ],
        ),
    ]
