# Generated by Django 5.0.1 on 2024-01-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0003_alter_battle_tournament'),
        ('user_management', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_battles', to='user_management.educatorprofile'),
            preserve_default=False,
        ),
    ]
