# Generated by Django 5.0.1 on 2024-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0004_battle_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
