# Generated by Django 5.0.1 on 2024-01-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0005_battle_active_tournament_active'),
        ('user_management', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='picture',
            field=models.CharField(default='binaryIcon.svg', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='invited_Educators',
            field=models.ManyToManyField(blank=True, related_name='invited_tournaments', to='user_management.educatorprofile'),
        ),
    ]
