# Generated by Django 5.0.1 on 2024-01-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0002_remove_tournament_battles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='tournament_management.tournament'),
        ),
    ]
