# Generated by Django 5.0.1 on 2024-01-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_github_integration', '0001_initial'),
        ('tournament_management', '0001_initial'),
        ('user_management', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament_management.battle'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to='user_management.studentprofile'),
        ),
    ]
