# Generated by Django 5.0.1 on 2024-02-03 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_github_integration', '0008_alter_team_code'),
        ('tournament_management', '0012_alter_battle_status_alter_tournament_status'),
        ('user_management', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functional_score', models.PositiveIntegerField(default=0)),
                ('timeliness_score', models.PositiveIntegerField(default=0)),
                ('manual_score', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('is_manual_evaluation', models.BooleanField(default=False)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_scores', to='tournament_management.battle')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_scores', to='team_github_integration.team')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='user_management.studentprofile')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_scores', to='tournament_management.tournament')),
            ],
        ),
    ]
