# Generated by Django 5.0.1 on 2024-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_userprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('educator', 'Educator'), ('student', 'Student')], default='educator', max_length=10),
            preserve_default=False,
        ),
    ]
