# Generated by Django 5.0.1 on 2024-01-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='battles',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='rankingScores',
        ),
        migrations.AddField(
            model_name='battle',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='tournament_management.tournament'),
        ),
    ]
