# Generated by Django 5.0.1 on 2024-01-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0006_tournament_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='picture',
            field=models.CharField(default='binaryIcon.svg', max_length=100),
        ),
        migrations.AddField(
            model_name='battle',
            name='software_project',
            field=models.FileField(default='', upload_to='software_projects/'),
            preserve_default=False,
        ),
    ]
